version: '3'
services:
  web:
    image: nginx
    environment:
     - VIRTUAL_HOST=fmc
    depends_on:
     - php
    restart: on-failure
    ports:
     - 80
    networks:
     - reverse-proxy
     - backnet
    volumes:
      - /var/www/html:/var/www/html
      - ./infra/nginx-internal/custom.conf:/etc/nginx/conf.d/custom.conf
  php:
    image: phpdockerio/php7-fpm
    networks:
      - backnet
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
      args:
        SRC_DIR: /var/www/html
        DOCKER_IMAGE_CONTEXT: infra/php
    restart: on-failure
    volumes:
      - /var/www/html:/var/www/html
    ports:
      - 9000
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
  adminer:
    image: adminer
    restart: always
    ports:
      - 8012:8080
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  backnet:
    driver: bridge